version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-app-version
    versions:
    - 4.0.0
  - dependency-name: ember-data-storefront
    versions:
    - 0.18.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: js-yaml
    versions:
    - 3.14.1
  - dependency-name: http-proxy
    versions:
    - 1.18.1
  - dependency-name: node-sass
    versions:
    - 4.14.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: jquery
    versions:
    - 3.5.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: morgan
    versions:
    - 1.10.0
  - dependency-name: tar
    versions:
    - 2.2.2
  - dependency-name: remarkable
    versions:
    - 1.7.4
  - dependency-name: mixin-deep
    versions:
    - 1.3.2
  - dependency-name: merge
    versions:
    - 1.2.1
  - dependency-name: lodash.merge
    versions:
    - 4.6.2
  - dependency-name: lodash.defaultsdeep
    versions:
    - 4.6.1
  - dependency-name: fstream
    versions:
    - 1.0.12
